### ISSUE TITLE
请问train_data.extend(train_data)是何作用？

### ISSUE THREAD

**Issue by DoliteMatheo** [bojone/dgcnn_for_reading_comprehension#1]
请问苏大佬，/dgcnn/dgcnn.py中第88行的train_data.extend(train_data)，将训练数据又复制一遍是何作用？谢谢！

**Comment by bojone** [comment]
将SogouQA和WebQA按2:1的比例混合。

**Comment by DoliteMatheo** [comment]
> 将SogouQA和WebQA按2:1的比例混合。

谢谢！那是因为SogouQA的数据比WebQA数据的噪声大，所以才要把它多训练一遍的吗？

**Comment by bojone** [comment]
对的。而且还因为valid用的是SogouQA的一部分。
