### ISSUE TITLE
如何添加test.py

### ISSUE THREAD

**Issue by Weigoss** [bojone/dgcnn_for_reading_comprehension#2]
苏神，打扰！请问在哪里可以添加test部分？谢谢

**Comment by bojone** [comment]
什么叫做“添加test部分”？

**Comment by Weigoss** [comment]
就是想做个demo，已经解决，谢谢大神 386761616 邮箱：386761616@qq.com 签名由 网易邮箱大师 定制 在2019年09月03日 14:53，苏剑林(Jianlin Su) 写道： 什么叫做“添加test部分”？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
